platform :ios, '8.0'
target 'Shop' do
pod 'AFNetworking', '~> 3.2.0'
pod 'SDWebImage', '~> 4.3.3'
pod 'Masonry', '~> 1.1.0'
pod 'FMDB', '~> 2.7.2'
pod 'SDCycleScrollView', '~> 1.75'
pod 'MJExtension', '~> 3.0.13'

pod 'UMengUShare/UI'
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod "SVProgressHUD-0.8.1"

end

