# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SUJIDANCI' do
pod'MJExtension'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'AVOSCloud'              
pod 'AVOSCloudIM'             
end
